language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
after_success:
  - julia -e 'cd(Pkg.dir("FunctionWrappers")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
